paths: {
  local: ${DREMIO_HOME}"/data"
  dist:  "file:///opt/dremio/dist"
}

services: {
  coordinator.enabled: true
  coordinator.master.enabled: true
  executor.enabled: false
  flight.use_session_service: true
}
