paths: {
  local: ${DREMIO_HOME}"/data"
  dist:  "file:///opt/dremio/dist"
}

services: {
  coordinator.enabled: false
  executor.enabled: true
  flight.use_session_service: true
}

zookeeper: "coordinator:2181"
